version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - TSRBerry

  - package-ecosystem: "github-actions"
    directory: ".github/actions/execute-command/"
    schedule:
      interval: weekly
    reviewers:
      - TSRBerry

  - package-ecosystem: "github-actions"
    directory: ".github/actions/setup-mako/"
    schedule:
      interval: weekly
    reviewers:
      - TSRBerry

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - TSRBerry
